name: Estrai Assets CAR
on: workflow_dispatch

jobs:
  extract-assets:
    runs-on: macos-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Scarica il file Assets da Pixeldrain
        run: |
          curl -L "https://pixeldrain.com/api/file/yGUJ7XXh" -o Assets.car

      - name: Compilazione ed Estrazione con Cartool
        run: |
          mkdir output_immagini
          
          # Scarica il tool affidabile
          git clone https://github.com/steventroughtonsmith/cartool.git
          
          # Compila il codice ignorando la firma digitale per evitare blocchi nel Cloud
          cd cartool
          xcodebuild -project cartool.xcodeproj -scheme cartool -configuration Release CONFIGURATION_BUILD_DIR=../build_output CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          cd ..
          
          # Lancia l'estrazione
          ./build_output/cartool Assets.car output_immagini

      - name: Comprime e prepara il Download
        run: zip -r assetti_estratti.zip output_immagini

      - name: Carica il file finale
        uses: actions/upload-artifact@v4
        with:
          name: pacchetto-assetti
          path: assetti_estratti.zip
